spring:
  datasource:
    url: jdbc:mysql://106.14.96.160:14498/oyr
    username: oyr
    password: J2bHLPkclzUFPfrs
    # url: jdbc:mysql://localhost:3306/oyr
    # username: root
    # password: root
  resources:
    cache:
      period: 604800 
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
  redis:
    port: 58295
    host: 106.14.96.160
    password: 6gV2S5KMNxKFFGjF
  cache:
    cache-names:
    - phones
    - area
    
logging:
  level:
    oyw.gp.oyr.mapper: trace
    
server:
  port: 1617



