spring:
  datasource:
    url: jdbc:mysql://106.14.96.160:3306/oyr
    username: root
    password: xihadajiang

logging:
  level:
#    root: warn
    oyw.gp.oyr.mapper: trace
  pattern:
    console: '%p%m%n'
    
server:
  port: 1617



