spring:
  datasource:
    url: jdbc:mysql://106.14.96.160:3306/oyr
    username: root
    password: xihadajiang
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
  cache:
    cache-names:
    - phones
    - area
    
logging:
  level:
    oyw.gp.oyr.mapper: trace
    
server:
  port: 1617



