spring:
  datasource:
    url: jdbc:mysql://106.14.96.160:3306/oyr
    username: root
    password: xihadajiang
    druid:
      enable: true
      initial-size: 5
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
      poolPreparedStatements: false # PScache false in MySql
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 1
      validation-query-timeout: 500
      filters: stat # monitor:stat / log:log4j / Sql-injection:wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
  cache:
    cache-names:
    - phones
    
logging:
  level:
    # root: warn
    oyw.gp.oyr.mapper: trace
    
server:
  port: 1617



